//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nUpdate.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nUpdate.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        public static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .NET Framework: ähnelt.
        /// </summary>
        public static string DotNetFrameworkText {
            get {
                return ResourceManager.GetString("DotNetFrameworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a download process running. ähnelt.
        /// </summary>
        public static string DownloadingProcessRunningExceptionText {
            get {
                return ResourceManager.GetString("DownloadingProcessRunningExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Deleting file &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string FileDeletingOperationText {
            get {
                return ResourceManager.GetString("FileDeletingOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Renaming file &quot;{0}&quot; to &quot;{1}&quot;...&quot; ähnelt.
        /// </summary>
        public static string FileRenamingOperationText {
            get {
                return ResourceManager.GetString("FileRenamingOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install ähnelt.
        /// </summary>
        public static string InstallButtonText {
            get {
                return ResourceManager.GetString("InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Copying {0}...&quot; ähnelt.
        /// </summary>
        public static string InstallerCopyingText {
            get {
                return ResourceManager.GetString("InstallerCopyingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Extracting files...&quot; ähnelt.
        /// </summary>
        public static string InstallerExtractingFilesText {
            get {
                return ResourceManager.GetString("InstallerExtractingFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The installer cannot overwrite the file &apos;{0}&apos; because it is being used by another process. Terminate all applications that block the access and try again by pressing &quot;OK&quot;. ähnelt.
        /// </summary>
        public static string InstallerFileInUseError {
            get {
                return ResourceManager.GetString("InstallerFileInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Error while iniaitializing the data.&quot; ähnelt.
        /// </summary>
        public static string InstallerInitializingErrorCaption {
            get {
                return ResourceManager.GetString("InstallerInitializingErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Error while updating the application&quot; ähnelt.
        /// </summary>
        public static string InstallerUpdatingErrorCaption {
            get {
                return ResourceManager.GetString("InstallerUpdatingErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file containing the update configuration is not a valid JSON-file and/or no data could be processed. ähnelt.
        /// </summary>
        public static string InvalidJsonExceptionText {
            get {
                return ResourceManager.GetString("InvalidJsonExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid signature data found. ähnelt.
        /// </summary>
        public static string InvalidSignatureErrorCaption {
            get {
                return ResourceManager.GetString("InvalidSignatureErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signature of the update package is not a valid RSA-signature. ähnelt.
        /// </summary>
        public static string InvalidSignatureErrorText {
            get {
                return ResourceManager.GetString("InvalidSignatureErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application&apos;s main folder could not be created. {0} ähnelt.
        /// </summary>
        public static string MainFolderCreationExceptionText {
            get {
                return ResourceManager.GetString("MainFolderCreationExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No network connection available. ähnelt.
        /// </summary>
        public static string NetworkConnectionExceptionText {
            get {
                return ResourceManager.GetString("NetworkConnectionExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accesses: ähnelt.
        /// </summary>
        public static string NewUpdateDialogAccessText {
            get {
                return ResourceManager.GetString("NewUpdateDialogAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available versions: {0} ähnelt.
        /// </summary>
        public static string NewUpdateDialogAvailableVersionsText {
            get {
                return ResourceManager.GetString("NewUpdateDialogAvailableVersionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog: ähnelt.
        /// </summary>
        public static string NewUpdateDialogChangelogText {
            get {
                return ResourceManager.GetString("NewUpdateDialogChangelogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current version: {0} ähnelt.
        /// </summary>
        public static string NewUpdateDialogCurrentVersionText {
            get {
                return ResourceManager.GetString("NewUpdateDialogCurrentVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File system ähnelt.
        /// </summary>
        public static string NewUpdateDialogFilesAccessText {
            get {
                return ResourceManager.GetString("NewUpdateDialogFilesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New updates can be downloaded for {0}. ähnelt.
        /// </summary>
        public static string NewUpdateDialogInfoText {
            get {
                return ResourceManager.GetString("NewUpdateDialogInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} new updates available. ähnelt.
        /// </summary>
        public static string NewUpdateDialogMultipleUpdatesHeader {
            get {
                return ResourceManager.GetString("NewUpdateDialogMultipleUpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processes ähnelt.
        /// </summary>
        public static string NewUpdateDialogProcessesAccessText {
            get {
                return ResourceManager.GetString("NewUpdateDialogProcessesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry ähnelt.
        /// </summary>
        public static string NewUpdateDialogRegistryAccessText {
            get {
                return ResourceManager.GetString("NewUpdateDialogRegistryAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        public static string NewUpdateDialogServicesAccessText {
            get {
                return ResourceManager.GetString("NewUpdateDialogServicesAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} new update available. ähnelt.
        /// </summary>
        public static string NewUpdateDialogSingleUpdateHeader {
            get {
                return ResourceManager.GetString("NewUpdateDialogSingleUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total package size: {0} ähnelt.
        /// </summary>
        public static string NewUpdateDialogSizeText {
            get {
                return ResourceManager.GetString("NewUpdateDialogSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no new updates available. ähnelt.
        /// </summary>
        public static string NoUpdateDialogHeader {
            get {
                return ResourceManager.GetString("NoUpdateDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application is currently up-to-date. ähnelt.
        /// </summary>
        public static string NoUpdateDialogInfoText {
            get {
                return ResourceManager.GetString("NoUpdateDialogInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating system: ähnelt.
        /// </summary>
        public static string OperatingSystemText {
            get {
                return ResourceManager.GetString("OperatingSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update package of version &quot;{0}&quot; could not be found. ähnelt.
        /// </summary>
        public static string PackageFileNotFoundExceptionText {
            get {
                return ResourceManager.GetString("PackageFileNotFoundExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The package file couldn&apos;t be found. ähnelt.
        /// </summary>
        public static string PackageNotFoundErrorText {
            get {
                return ResourceManager.GetString("PackageNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The package size couldn&apos;t be calculated because an unknown error appeared. Possibly the package file does not exist. ähnelt.
        /// </summary>
        public static string PackageSizeCalculationExceptionText {
            get {
                return ResourceManager.GetString("PackageSizeCalculationExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while checking the package&apos;s signature. ähnelt.
        /// </summary>
        public static string PackageValidityCheckErrorCaption {
            get {
                return ResourceManager.GetString("PackageValidityCheckErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Starting process &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string ProcessStartOperationText {
            get {
                return ResourceManager.GetString("ProcessStartOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Terminating process &quot;{1}&quot;...&quot; ähnelt.
        /// </summary>
        public static string ProcessStopOperationText {
            get {
                return ResourceManager.GetString("ProcessStopOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Deleting name-value-pair &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string RegistryNameValuePairDeleteValueOperationText {
            get {
                return ResourceManager.GetString("RegistryNameValuePairDeleteValueOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Setting value of &quot;{0}&quot; in the registry to &quot;{1}&quot;...&quot; ähnelt.
        /// </summary>
        public static string RegistryNameValuePairSetValueOperationText {
            get {
                return ResourceManager.GetString("RegistryNameValuePairSetValueOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Creating registry subkey &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string RegistrySubKeyCreateOperationText {
            get {
                return ResourceManager.GetString("RegistrySubKeyCreateOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Deleting registry subkey &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string RegistrySubKeyDeleteOperationText {
            get {
                return ResourceManager.GetString("RegistrySubKeyDeleteOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required version: ähnelt.
        /// </summary>
        public static string RequiredVersionText {
            get {
                return ResourceManager.GetString("RequiredVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a search process running. ähnelt.
        /// </summary>
        public static string SearchProcessRunningExceptionText {
            get {
                return ResourceManager.GetString("SearchProcessRunningExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Starting service &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string ServiceStartOperationText {
            get {
                return ResourceManager.GetString("ServiceStartOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Stopping service &quot;{0}&quot;...&quot; ähnelt.
        /// </summary>
        public static string ServiceStopOperationText {
            get {
                return ResourceManager.GetString("ServiceStopOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nUpdate will cancel the installation of the update packages and delete them unrecoverably. ähnelt.
        /// </summary>
        public static string SignatureNotMatchingErrorText {
            get {
                return ResourceManager.GetString("SignatureNotMatchingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while trying to transfer data for the statistics. Please report this problem to the developer of the program in order to make him capable of fixing it. Response from the PHP-script: {0} ähnelt.
        /// </summary>
        public static string StatisticsScriptExceptionText {
            get {
                return ResourceManager.GetString("StatisticsScriptExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing requirements. ähnelt.
        /// </summary>
        public static string UnfulfilledRequirementErrorCaption {
            get {
                return ResourceManager.GetString("UnfulfilledRequirementErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The installation of some updates can&apos;t be completed because the following requirements are unfulfilled: ähnelt.
        /// </summary>
        public static string UnfulfilledRequirementErrorText {
            get {
                return ResourceManager.GetString("UnfulfilledRequirementErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading updates... ähnelt.
        /// </summary>
        public static string UpdateDownloadDialogLoadingHeader {
            get {
                return ResourceManager.GetString("UpdateDownloadDialogLoadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait while the available updates are
        ///downloaded...  ({0}%) ähnelt.
        /// </summary>
        public static string UpdateDownloadDialogLoadingInfo {
            get {
                return ResourceManager.GetString("UpdateDownloadDialogLoadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching for updates... ähnelt.
        /// </summary>
        public static string UpdateSearchDialogHeader {
            get {
                return ResourceManager.GetString("UpdateSearchDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while searching for updates. ähnelt.
        /// </summary>
        public static string UpdateSearchErrorCaption {
            get {
                return ResourceManager.GetString("UpdateSearchErrorCaption", resourceCulture);
            }
        }
    }
}
