using System.Reflection;
using nUpdate.Administration.Core.Security;

namespace nUpdate.Administration.Core.Statistics;

/// <summary>
///     The server-side statistics API v2: a fixed PHP script plus a generated configuration file. The names differ from
///     the <c>statistics.php</c> of nUpdate 3 and 4, so both scripts can serve their clients from the same folder.
/// </summary>
public static class StatisticsScript
{
    public const string ScriptFileName = "nupdate-statistics.php";

    public const string ConfigFileName = "nupdate-statistics.config.php";

    /// <summary>The script nUpdate Administration 3 and 4 uploaded next to <c>updates.json</c>.</summary>
    public const string LegacyScriptFileName = "statistics.php";

    /// <summary>The PHP script that is uploaded unchanged next to the feed.</summary>
    public static string Script { get; } = ReadEmbedded();

    /// <summary>Renders the configuration the script includes. The admin secret is stored as a SHA-256 hash.</summary>
    public static string RenderConfig(string dbHost, string dbName, string dbUser, string dbPassword,
        string adminSecret)
    {
        ArgumentNullException.ThrowIfNull(dbHost);
        ArgumentNullException.ThrowIfNull(dbName);
        ArgumentNullException.ThrowIfNull(dbUser);
        ArgumentNullException.ThrowIfNull(dbPassword);
        ArgumentException.ThrowIfNullOrEmpty(adminSecret);

        return "<?php\n" +
               "// Generated by nUpdate Administration. Keep this file next to nupdate-statistics.php.\n" +
               $"$nupdateDbHost = {Quote(dbHost)};\n" +
               $"$nupdateDbName = {Quote(dbName)};\n" +
               $"$nupdateDbUser = {Quote(dbUser)};\n" +
               $"$nupdateDbPassword = {Quote(dbPassword)};\n" +
               $"$nupdateAdminSecretHash = {Quote(SecretGenerator.HashSecret(adminSecret))};\n";
    }

    private static string Quote(string value) => "'" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("'", "\\'", StringComparison.Ordinal) + "'";

    private static string ReadEmbedded()
    {
        // The script is embedded by the project file; a missing resource is a build defect, not a runtime condition.
        using var stream = typeof(StatisticsScript).GetTypeInfo().Assembly
            .GetManifestResourceStream("nUpdate.Administration.Core.Resources.nupdate-statistics.php")!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
