<?php
/*
 * nUpdate statistics API, version 2. Generated by nUpdate Administration; do not edit by hand.
 *
 * Routes (below nupdate-statistics.php, resolved from PATH_INFO):
 *   GET    /v2                                      -> {"api":"nupdate-statistics","version":2}       (public)
 *   POST   /v2/downloads                            body {"projectId","version","os"} -> 204          (clients, public; 404 for a version that is not registered)
 *   GET    /v2/projects/{id}/statistics             Bearer <secret> -> {"total","versions":[...]}
 *   PUT    /v2/projects/{id}/versions/{version}     Bearer <secret> -> 204
 *   DELETE /v2/projects/{id}/versions/{version}     Bearer <secret> -> 204
 *   DELETE /v2/projects/{id}                        Bearer <secret> -> 204
 *
 * Errors are {"error":{"code":"...","message":"..."}} with 400, 401, 404, 405, 415 or 500.
 * The admin secret may also be sent as X-nUpdate-Secret for hosts that strip the Authorization header.
 */

declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

$configFile = __DIR__ . '/nupdate-statistics.config.php';
if (!is_file($configFile)) {
    fail(500, 'configuration_missing', 'nupdate-statistics.config.php is missing.');
}
require $configFile;
foreach (['nupdateDbHost', 'nupdateDbName', 'nupdateDbUser', 'nupdateDbPassword', 'nupdateAdminSecretHash'] as $setting) {
    if (!isset($$setting) || !is_string($$setting)) {
        fail(500, 'configuration_missing', "nupdate-statistics.config.php does not define \$$setting.");
    }
}

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

$method = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');
$segments = routeSegments();

try {
    if ($segments === ['v2']) {
        requireMethod($method, ['GET']);
        echo json_encode(['api' => 'nupdate-statistics', 'version' => 2]);
    } elseif ($segments === ['v2', 'downloads']) {
        requireMethod($method, ['POST']);
        $body = readJsonBody();
        $projectId = normalizeGuid((string)($body['projectId'] ?? ''));
        $version = substr(trim((string)($body['version'] ?? '')), 0, 64);
        $os = substr(trim((string)($body['os'] ?? 'Unknown')), 0, 64);
        if ($projectId === null || $version === '') {
            fail(400, 'invalid_request', 'projectId and version are required.');
        }
        $db = connect();
        // Anyone can report, so only versions the administration registered are counted.
        $stmt = $db->prepare('SELECT 1 FROM nupdate_version WHERE project_id = ? AND version = ?');
        $stmt->bind_param('ss', $projectId, $version);
        $stmt->execute();
        if ($stmt->get_result()->fetch_row() === null) {
            fail(404, 'unknown_version', 'The version is not registered for this project.');
        }
        $stmt = $db->prepare('INSERT INTO nupdate_download (project_id, version, os, reported_at) VALUES (?, ?, ?, UTC_TIMESTAMP())');
        $stmt->bind_param('sss', $projectId, $version, $os);
        $stmt->execute();
        http_response_code(204);
    } elseif (count($segments) >= 3 && $segments[0] === 'v2' && $segments[1] === 'projects') {
        $projectId = normalizeGuid($segments[2]);
        if ($projectId === null) {
            fail(400, 'invalid_project', 'The project id is not a GUID.');
        }
        $rest = array_slice($segments, 3);
        if ($rest === []) {
            requireMethod($method, ['DELETE']);
            requireAdmin();
            $db = connect();
            foreach (['nupdate_download', 'nupdate_version'] as $table) {
                $stmt = $db->prepare("DELETE FROM $table WHERE project_id = ?");
                $stmt->bind_param('s', $projectId);
                $stmt->execute();
            }
            http_response_code(204);
        } elseif ($rest === ['statistics']) {
            requireMethod($method, ['GET']);
            requireAdmin();
            echo json_encode(statistics(connect(), $projectId));
        } elseif (count($rest) === 2 && $rest[0] === 'versions') {
            requireMethod($method, ['PUT', 'DELETE']);
            requireAdmin();
            $version = substr(trim($rest[1]), 0, 64);
            if ($version === '') {
                fail(400, 'invalid_version', 'The version is empty.');
            }
            $db = connect();
            if ($method === 'PUT') {
                $stmt = $db->prepare('INSERT INTO nupdate_version (project_id, version, created_at) VALUES (?, ?, UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE created_at = created_at');
                $stmt->bind_param('ss', $projectId, $version);
                $stmt->execute();
            } else {
                foreach (['nupdate_download', 'nupdate_version'] as $table) {
                    $stmt = $db->prepare("DELETE FROM $table WHERE project_id = ? AND version = ?");
                    $stmt->bind_param('ss', $projectId, $version);
                    $stmt->execute();
                }
            }
            http_response_code(204);
        } else {
            fail(404, 'not_found', 'Unknown route.');
        }
    } else {
        fail(404, 'not_found', 'Unknown route.');
    }
} catch (mysqli_sql_exception $e) {
    error_log('nUpdate statistics: ' . $e->getMessage());
    fail(500, 'database_error', 'Database error.');
}

function routeSegments(): array
{
    // PATH_INFO is already decoded by the web server; the REQUEST_URI fallback is not.
    $path = $_SERVER['PATH_INFO'] ?? $_SERVER['ORIG_PATH_INFO'] ?? '';
    $decode = static fn (string $segment): string => $segment;
    if ($path === '') {
        $script = $_SERVER['SCRIPT_NAME'] ?? '';
        $uri = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?? '';
        if ($script !== '' && strpos($uri, $script) === 0) {
            $path = substr($uri, strlen($script));
            $decode = 'rawurldecode';
        }
    }
    return array_values(array_map($decode, array_filter(explode('/', $path), static fn (string $segment): bool => $segment !== '')));
}

function connect(): mysqli
{
    global $nupdateDbHost, $nupdateDbName, $nupdateDbUser, $nupdateDbPassword;
    $db = new mysqli($nupdateDbHost, $nupdateDbUser, $nupdateDbPassword, $nupdateDbName);
    $db->set_charset('utf8mb4');
    $db->query('CREATE TABLE IF NOT EXISTS nupdate_version (project_id CHAR(36) NOT NULL, version VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (project_id, version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $db->query('CREATE TABLE IF NOT EXISTS nupdate_download (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, project_id CHAR(36) NOT NULL, version VARCHAR(64) NOT NULL, os VARCHAR(64) NOT NULL, reported_at DATETIME NOT NULL, INDEX idx_project_version (project_id, version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    return $db;
}

function statistics(mysqli $db, string $projectId): array
{
    $versions = [];
    $stmt = $db->prepare('SELECT version FROM nupdate_version WHERE project_id = ? ORDER BY created_at');
    $stmt->bind_param('s', $projectId);
    $stmt->execute();
    $result = $stmt->get_result();
    while ($row = $result->fetch_assoc()) {
        $versions[$row['version']] = ['version' => $row['version'], 'downloads' => 0, 'byOperatingSystem' => new stdClass()];
    }
    $stmt = $db->prepare('SELECT version, os, COUNT(*) AS downloads FROM nupdate_download WHERE project_id = ? GROUP BY version, os');
    $stmt->bind_param('s', $projectId);
    $stmt->execute();
    $result = $stmt->get_result();
    $total = 0;
    while ($row = $result->fetch_assoc()) {
        $version = $row['version'];
        if (!isset($versions[$version])) {
            continue; // reported before its version was unregistered
        }
        $count = (int)$row['downloads'];
        $versions[$version]['downloads'] += $count;
        $versions[$version]['byOperatingSystem']->{$row['os']} = $count;
        $total += $count;
    }
    return ['total' => $total, 'versions' => array_values($versions)];
}

function requireAdmin(): void
{
    global $nupdateAdminSecretHash;
    $header = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
    if ($header === '' && function_exists('apache_request_headers')) {
        $headers = apache_request_headers();
        $header = $headers['Authorization'] ?? $headers['authorization'] ?? '';
    }
    if ($header === '' && ($_SERVER['HTTP_X_NUPDATE_SECRET'] ?? '') !== '') {
        $header = 'Bearer ' . $_SERVER['HTTP_X_NUPDATE_SECRET'];
    }
    if (!preg_match('/^Bearer\s+(\S+)$/i', $header, $matches) || !hash_equals($nupdateAdminSecretHash, hash('sha256', $matches[1]))) {
        fail(401, 'unauthorized', 'Invalid or missing admin secret.');
    }
}

function requireMethod(string $actual, array $allowed): void
{
    if (!in_array($actual, $allowed, true)) {
        header('Allow: ' . implode(', ', $allowed));
        fail(405, 'method_not_allowed', "Method $actual is not allowed for this route.");
    }
}

function readJsonBody(): array
{
    $type = $_SERVER['CONTENT_TYPE'] ?? $_SERVER['HTTP_CONTENT_TYPE'] ?? '';
    if ($type !== '' && stripos($type, 'application/json') !== 0) {
        fail(415, 'unsupported_media_type', 'The request body must be application/json.');
    }
    $raw = file_get_contents('php://input');
    if ($raw === false || trim($raw) === '') {
        return [];
    }
    $data = json_decode($raw, true);
    if (!is_array($data)) {
        fail(400, 'invalid_json', 'The request body is not valid JSON.');
    }
    return $data;
}

function normalizeGuid(string $value): ?string
{
    $value = strtolower(trim($value));
    return preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', $value) === 1 ? $value : null;
}

function fail(int $status, string $code, string $message): void
{
    http_response_code($status);
    echo json_encode(['error' => ['code' => $code, 'message' => $message]]);
    exit;
}
