<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>nUpdate is a powerful and secure update system for .NET applications. Contains the client library and the contracts shared with the update installer and nUpdate Administration.</Description>
    <PackageTags>update;updater;auto-update;installer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" LogicalName="nUpdate.Localization.%(Filename).json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Security.Cryptography.Cng" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="nUpdate.Tests" />
    <InternalsVisibleTo Include="nUpdate.UpdateInstaller" />
    <InternalsVisibleTo Include="nUpdate.Administration.Core" />
    <InternalsVisibleTo Include="nUpdate.Administration" />
    <InternalsVisibleTo Include="nUpdate.UI.WindowsForms" />
    <InternalsVisibleTo Include="nUpdate.UI.WPF" />
    <InternalsVisibleTo Include="nUpdate.UI.Avalonia" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
